services:
  nextjs-app:
    build:
      context: ./nextjs-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - internal_network
    environment:
      - NEXT_PUBLIC_NODE_URL=http://node-backend:9000/api
    volumes:
      - ./nextjs-frontend:/app

  node-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - "9000:9000"
    networks:
      - internal_network

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - internal_network
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: $MONGODB_DATABASE
    volumes:
    - db:/data/db

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - "8081:8081"
#    networks:
#      - internal_network
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGODB_USER
#      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGODB_PASSWORD
#      ME_CONFIG_MONGODB_SERVER: mongo


networks:
  internal_network:
    driver: bridge

volumes:
  db:
