version: '3.8'

services:
  nextjs-app:
    build:
      context: ./nextjs-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - internal_network

  node-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    networks:
      - internal_network

#  mongodb:
#    image: mongo
#    ports:
#      - "27017:27017"
#    networks:
#      - internal_network
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root_user
#      - MONGO_INITDB_ROOT_PASSWORD=root_password

networks:
  internal_network:
    driver: bridge
