name: Code Review
on:
  pull_request:
    branches:
      - main  # or whichever branch you want to protect

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - uses: sshnaidm/gpt-code-review-action@v2.0
        with:
          openai-key: ${{ secrets.OPENAI_API_KEY }}
          max-length: 4000
          prompt: 'Only suggest performance and readability improvements and naming conventions for this code.'
